# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, verbose_name='DNI')),
                ('license', models.CharField(max_length=16, verbose_name='Carnet')),
                ('license_expiration', models.DateField(verbose_name='Fecha de vencimiento')),
                ('address', models.CharField(max_length=200, verbose_name='Direcci\xf3n')),
                ('phone_number', models.CharField(max_length=16, verbose_name='Tel\xe9fono')),
                ('student_file', models.PositiveIntegerField(verbose_name='Legajo')),
                ('credits', models.IntegerField(verbose_name='Cr\xe9ditos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('shift', models.CharField(choices=[('m', 'Ma\xf1ana'), ('t', 'Tarde')], max_length=1, verbose_name='Turno')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comment', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
