# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('c', 'Confirmada'), ('p', 'Pendiente'), ('c', 'Cancelada')], default='c', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='bookerprofile',
            name='credits',
            field=models.IntegerField(default=0, verbose_name='Cr\xe9ditos'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='shift',
            field=models.CharField(choices=[('m', 'Ma\xf1ana'), ('t', 'Tarde')], default='m', max_length=1, verbose_name='Turno'),
        ),
    ]
