# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20160105_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookerprofile',
            name='debit_credits',
            field=models.BooleanField(default=False, verbose_name='Debitar cr\xe9ditos'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('c', 'Confirmada'), ('p', 'Pendiente'), ('x', 'Cancelada')], default='c', max_length=1, verbose_name='Estado'),
        ),
    ]
