# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 03:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20160106_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AddField(
            model_name='booking',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 7, 0, 19, 51, 723099), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 7, 0, 20, 8, 832433), verbose_name='modified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookerprofile',
            name='credits',
            field=models.IntegerField(default=1000, verbose_name='Cr\xe9ditos'),
        ),
    ]
