# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-01 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20160107_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=90, verbose_name='Descripci\xf3n')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bookerprofile',
            name='credits',
            field=models.IntegerField(default=0, verbose_name='Cr\xe9ditos'),
        ),
    ]
